### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Bamboozul** [Liz-chan/sink-for-everyone#3]
I'm not sure if it's just me, but I've been having this problem for a while now, and the only solution that I've found is to uninstall and reinstall.

 
![Screenshot_20230805-145530_Nova Launcher_1](https://github.com/Liz-chan/sink-for-everyone/assets/101983929/e8c74324-0bdd-4cab-afce-04f0f4273b57)

**Comment by Liz-chan** [comment]
I  haven't had any issues with it personally. It's supposed to be based on the DRM-free version by LJ, so nothing I can really do there.

**Comment by Bamboozul** [comment]
Perhaps it's because I'm running AOSP Android 13. Anyway, thank you very much.
